import {ClerkProvider} from "@clerk/nextjs";
import type {Metadata} from "next";
import "./globals.css";
import {GeistSans} from 'geist/font/sans'
import {dark} from "@clerk/themes";
import {ThemeProvider} from "@/components/theme-provider";
import {Toaster} from "sonner";
import {NextSSRPlugin} from "@uploadthing/react/next-ssr-plugin";
import {extractRouterConfig} from "uploadthing/server";

import {ourFileRouter} from "@/app/api/uploadthing/core";

export const metadata: Metadata = {
    title: "Project V",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <ClerkProvider afterSignOutUrl={"/"} appearance={{baseTheme: dark}}>
            <html lang="en" className={GeistSans.className}>
            <body>
            <ThemeProvider attribute={"class"} forcedTheme={"dark"} storageKey={"project-v-theme"}>
                <Toaster theme={"light"} position={"bottom-center"}/>

                <NextSSRPlugin
                    /**
                    * The `extractRouterConfig` will extract **only** the route configs
                    * from the router to prevent additional information from being
                    * leaked to the client. The data passed to the client is the same
                    * as if you were to fetch `/api/uploadthing` directly.
                    */
                    routerConfig={extractRouterConfig(ourFileRouter)}
                />
                {children}
            </ThemeProvider>
            </body>
            </html>
        </ClerkProvider>
    );
}